### ISSUE TITLE
Register and Edit Profile: Format validations for Contact Number is not consistent

### ISSUE THREAD

**Issue by seppjooo** [ploidddddd/purplekeep#27]
This results with the format from the Register Account saved and when trying to Edit Profile, the user will then have to edit the format of his Contact Number. I think using one consistent format is better.

Register Account:
![register](https://user-images.githubusercontent.com/20873957/36350304-5acdb6f6-14d1-11e8-8d90-304672e79a83.png)

Edit Profile:
![edit](https://user-images.githubusercontent.com/20873957/36350302-4bd5cb3e-14d1-11e8-9815-117b6477757e.png)

**Comment by chinn015** [comment]
fixed by: Christine Diane Malazarte
size : 3
commit id: 665c556

**Comment by jenadrianne** [comment]
STILL AN ISSUE 
EDIT PROFILE 
![image](https://user-images.githubusercontent.com/23441105/37134839-4518df40-22d5-11e8-9d90-e129d48ddf7f.png)
CREATE ACCOUNT 
![image](https://user-images.githubusercontent.com/23441105/37134848-4d4f5cd4-22d5-11e8-968b-d2bbd2391a71.png)
